categories:
  - "Saving Account"
  - "JEPI"
  - "OXY"
  - "CRYPTO"
  - "Expense claims"
  - "Nordea Credit Card"
  - "Full-time job (net)"
  - "Labour market contribution"
  - "Taxes"
  - "Rent (monthly)"
  - "Mom"
  - "Dad"
  - "Shopping (monthly)"
  - "Food& Drinks (monthly)"
  - "Lunch (monthly)"
  - "Cleaning costs (monthly)"
  - "Disney+"
  - "Louis Nielsen"
  - "Apple Cloud"
  - "Fitness center membership (monthly)"
  - "Google Cloud"
  - "Max (yearly)"
  - "Metro (monthly)"
  - "House insurance Tryg (yearly, in Jan)"
  - "Akasse"
  - "Liability insurance (yearly, in Apr)"
  - "Mobile phone (monthly)"
  - "Traveling"
  - "Banking account fees (monthly)"
  - "Annuity K43"
  - "Annuity M12"
  - "Stock investment plan"

aliases:
  Rent: "Rent (monthly)"
  Shopping: "Shopping (monthly)"
  "Food & Drinks": "Food& Drinks (monthly)"
  Food: "Food& Drinks (monthly)"
  Lunch: "Lunch (monthly)"
  "Fitness center membership": "Fitness center membership (monthly)"
  Metro: "Metro (monthly)"
  "Mobile phone": "Mobile phone (monthly)"
  "Banking account fees": "Banking account fees (monthly)"
